import { Ionicons } from "@expo/vector-icons";
import { ScrollView, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { CircularProgress } from "../components/CircularProgress";
import { FloatingBottomNav } from "../components/FloatingBottomNav";
import { COLORS, FONTS } from "../theme/colors";

function Stage({ label, status, muted }: { label: string; status: string; muted?: boolean }) { return <View className="flex-row items-center mb-3"><View className="w-2 h-2 rounded-full mr-3" style={{ backgroundColor: muted ? "#DCE4D9" : "#426800" }} /><Text className="flex-1 text-[12px]" style={{ color: muted ? "#AAB7A6" : COLORS.headingDark, fontFamily: FONTS.semiBold }}>{label}</Text><Text className="text-[10px]" style={{ color: muted ? "#D0D9CD" : "#A3B29B", fontFamily: FONTS.bold }}>{status}</Text></View>; }

export default function Tracker() {
  const insets = useSafeAreaInsets();
  return <View className="flex-1 bg-[#F4F6EF]"><ScrollView showsVerticalScrollIndicator={false} className="px-6" contentContainerStyle={{ paddingTop: Math.max(insets.top, 20) + 18, paddingBottom: Math.max(insets.bottom, 20) + 100 }}>
    <View className="flex-row items-center justify-between mb-6"><Text className="text-[21px] text-[#203E20]" style={{ fontFamily: FONTS.bold }}>My Tracker</Text><TouchableOpacity className="w-10 h-10 rounded-2xl bg-white items-center justify-center" accessibilityRole="button" accessibilityLabel="Add application"><Ionicons name="add" size={24} color="#203E20" /></TouchableOpacity></View>
    <View className="h-[203px] rounded-[39px] bg-[#193E1C] px-8 pt-8 mb-8 overflow-hidden"><View className="absolute w-44 h-44 rounded-full bg-[#2F572B] right-[-25px] top-[43px]" /><View className="absolute w-36 h-36 rounded-full bg-[#3C6335] right-[-2px] top-[92px] opacity-70" /><Text className="text-[10px] tracking-[1px] text-[#B0C1AB]" style={{ fontFamily: FONTS.bold }}>TOTAL FUNDING POTENTIAL</Text><Text className="text-[36px] text-white mt-2" style={{ fontFamily: FONTS.bold }}>$128,450</Text><View className="flex-row items-center mt-8"><View className="mr-8"><Text className="text-[25px] text-white" style={{ fontFamily: FONTS.bold }}>08</Text><Text className="text-[9px] tracking-[.7px] text-[#B0C1AB]" style={{ fontFamily: FONTS.bold }}>ACTIVE APPS</Text></View><View className="w-px h-8 bg-[#53714D] mr-8" /><View><Text className="text-[25px] text-white" style={{ fontFamily: FONTS.bold }}>03</Text><Text className="text-[9px] tracking-[.7px] text-[#B0C1AB]" style={{ fontFamily: FONTS.bold }}>INTERVIEWS</Text></View></View></View>
    <Text className="text-[14px] tracking-[1px] text-[#29472A] mb-6 ml-2" style={{ fontFamily: FONTS.bold }}>ONGOING APPLICATIONS</Text>
    <View className="bg-white rounded-[36px] p-6 mb-6"><View className="flex-row items-center justify-between"><View className="flex-row items-center flex-1 mr-2"><View className="w-14 h-14 rounded-2xl bg-[#073B31] items-center justify-center mr-4"><Ionicons name="shield-checkmark-outline" size={29} color="#1F7560" /></View><View className="flex-1"><Text className="text-[16px] leading-5 text-[#29472A]" style={{ fontFamily: FONTS.bold }}>Chevening{"\n"}Scholarship</Text><Text className="text-[10px] tracking-[.8px] text-[#A3B29B] mt-1" style={{ fontFamily: FONTS.bold }}>UNITED KINGDOM</Text></View></View><CircularProgress progress={75} size={50} strokeWidth={6} progressColor="#426800" trackColor="#EEF1EC" /></View><View className="mt-6"><Stage label="Documents Verified" status="COMPLETED" /><Stage label="Initial Screening" status="PASSED" /><Stage label="Personal Interview" status="UPCOMING" muted /></View><TouchableOpacity className="bg-[#F3F5F0] rounded-[17px] h-11 items-center justify-center mt-2" accessibilityRole="button"><Text className="text-[10px] tracking-[.8px] text-[#29472A]" style={{ fontFamily: FONTS.bold }}>VIEW HISTORY</Text></TouchableOpacity></View>
    <View className="bg-white rounded-[36px] p-6"><View className="flex-row items-center justify-between"><View className="flex-row items-center flex-1 mr-2"><View className="w-14 h-14 rounded-2xl bg-[#363636] items-center justify-center mr-4"><Ionicons name="globe-outline" size={25} color="#94866B" /></View><View className="flex-1"><Text className="text-[16px] text-[#29472A]" style={{ fontFamily: FONTS.bold }}>Fulbright Program</Text><Text className="text-[10px] tracking-[.8px] text-[#A3B29B] mt-1" style={{ fontFamily: FONTS.bold }}>UNITED STATES</Text></View></View><CircularProgress progress={30} size={50} strokeWidth={6} progressColor="#426800" trackColor="#EEF1EC" /></View><View className="flex-row items-center rounded-xl bg-[#FFF6F1] border border-[#FFE1D0] px-3 h-11 mt-6"><Ionicons name="alert-circle-outline" size={16} color="#FF6B29" /><Text className="text-[10px] text-[#D9541B] ml-3" style={{ fontFamily: FONTS.bold }}>MISSING RECOMMENDATION LETTER</Text></View><TouchableOpacity className="h-11 rounded-[17px] bg-[#31532A] items-center justify-center mt-6" accessibilityRole="button"><Text className="text-[10px] tracking-[.8px] text-white" style={{ fontFamily: FONTS.bold }}>UPDATE NOW</Text></TouchableOpacity></View>
  </ScrollView><FloatingBottomNav currentTab="grid" /></View>;
}
